### ISSUE TITLE
candidate base: perf

### ISSUE THREAD

**Issue by yarikoptic** [con/duct#1]
part of linux https://perf.wiki.kernel.org/index.php/Main_Page

concerns:
- might come with a notable performance hit.  Possible "workaround" - disable anything what is not relevant to our desired metrics: memory, cpu,

**Comment by asmacdo** [comment]
Desired Metrics:
 - Max CPU
 - Max Memory

**Comment by asmacdo** [comment]
From what I saw `perf` would not do well for this. The metrics it collects on memory are counters, such as cache misses, rather than memory consumed.
