### ISSUE TITLE
Re-enable osx tests

### ISSUE THREAD

**Issue by asmacdo** [con/duct#15]
https://github.com/con/duct/pull/14/files#diff-245392b692a50c38ecab4381b118862db514035c10983f3bd4f4b7f1f4be4692R27-R31

Disabled to keep the matrix small during development.

**Comment by asmacdo** [comment]
Tests failed on OSX 12 with python 3.8

- Looks like the tmpdir fixture isn't working right? `KeyError: 'USER' `
- Maybe some bad process/thread handling, but could also be bad exception handling of ^

[mac_fail_ghaction.log](https://github.com/user-attachments/files/15686553/mac_fail_ghaction.log)

**Comment by yarikoptic** [comment]
odd, in principle there is USER variable on OSX

```
$> ssh datalads-imac2.kiewit.dartmouth.edu
Last login: Wed May 29 15:49:39 2024
yoh@datalads-imac2 ~ % export | grep USER
USER=yoh
```

**but** in general it would be more robust to use `os.environ.get(X)` instead of `os.environ[X]` so users do not get little tool blow into their faces happen tool's expectations of having some env vars not met.

**Comment by asmacdo** [comment]
+1, thats what I ended up doing.
