### ISSUE TITLE
Investigate pytest.CaptureFixture usage problem

### ISSUE THREAD

**Issue by asmacdo** [con/duct#160]
Our `test/test_execution.py::test_outputs_none_quiet` uses the pytest capture fixture to capture the logs to stderr. This works just fine as long is it is the only usage.

I added a second (identical) test, which fails 
```
>       assert "Summary" in caplog.text
E       AssertionError: assert 'Summary' in ''
E        +  where '' = <_pytest.logging.LogCaptureFixture object at 0x7f577401bbd0>.text
```

So it looks like this fixture isn't being properly reset between tests. 

For https://github.com/con/duct/pull/159, it turned out to be better just to add a 3rd execution to the same test.

Additionally, this test should be very quick, but it still takes over 2 seconds to run. We should check out this fixture and make sure we are using it correctly. @yarikoptic wdyt?

**Comment by yarikoptic** [comment]
would `caplog.clear()` help? 

as for slow -- are you sure it is not 2 sec of duct's execute?  I would expect fixture to be quick.

**Comment by asmacdo** [comment]
`caplog.clear()` doesnt help, but you're correct about the speed. that one is running the test script with duration 1 twice. 2 seconds makes perfect sense

**Comment by asmacdo** [comment]
I'm going to close-- if we need to use this more than once, the issue will make itself known.
