### ISSUE TITLE
add all output file paths to the info.json

### ISSUE THREAD

**Issue by asmacdo** [con/duct#165]
Let's make info.json the top-level file, so we add file paths, explicitly linking the files.

Also possible to add any relevant metadata regarding each file

(I have in mind the duct output, but would it be helpful to include  files that the command produced?)

usage.json
 - path
 - schema version

stdout/err
 - path
 - (if we ever have various ways to pipe this, good to record here)

**Comment by yarikoptic** [comment]
Good idea.
