### ISSUE TITLE
Option to make <summary_format> still flexible for user 

### ISSUE THREAD

**Issue by asmacdo** [con/duct#172]
@yarikoptic since you seem attached to the summary_format  The user can set a `str`, (note, not an f string) https://github.com/con/duct/blob/main/src/con_duct/__main__.py#L31-L46

Since the user-provided value is a regular string, we cannot use fancing f-string logic.

Instead we could add the logic to what I'm calling the  "human readable preserializer" https://github.com/con/duct/blob/main/src/con_duct/__main__.py#L472-L476. That serializer is currently only responsible for replacing "unknown" string when the value is None, but it could be extended to do any other logic that would be necessary, ie rounding, and possibly even adding unit choices (ie Gb instead of bytes).

This would leave the user-customizable string to much simpler, and only allow the usage of pre-formatted values.

**Comment by yarikoptic** [comment]
here is the format helper I pointed out in matrix yesterday:

> FWIW here is the formatter I was talking about I did for datalad probably 10 years ago by now: https://github.com/datalad/datalad-deprecated/blob/master/datalad_deprecated/ls.py#L369 . And then here how those formatters were used: https://github.com/datalad/datalad-deprecated/blob/master/datalad_deprecated/ls.py#L484 . So it seems we could easily allow for some !S for humanize.naturalsize wrapping around that value. and the construct for unknown I already gave you. Moreover there for percents we could even color similarly to how dstat does , ie. making them red if getting close to 100% or above.
> Do look at that code and see how ansi_colors where used etc - might come handy

I think it provides a very nice helper also to output "unknown" for `None` etc while concentrating all that formatting logic in the formatter instead of diluting through the code like proposed in

- #181
