### ISSUE TITLE
Prepare release to PyPI

### ISSUE THREAD

**Issue by asmacdo** [con/duct#42]
Lets push it to the cheese shop!

Prerequisites:
 - `con-duct` on PyPI
 - `con_duct` for python package name
 - keep `duct` as entrypoint

Do the actual release  with automation https://github.com/con/duct/issues/7

**Comment by yarikoptic** [comment]
Is there any progress on this?

**Comment by asmacdo** [comment]
I didn't hear back from the GitHub project owner yet but the PyPI project owner has been responsive and is trying to contact the GitHub Repo owner through another channel.

**Comment by asmacdo** [comment]
Got `con-duct` approved upstream. https://github.com/pypi/support/issues/4360#event-13444739693
