### ISSUE TITLE
add [--] into --help output

### ISSUE THREAD

**Issue by yarikoptic** [con/duct#51]
so instead of
```
usage: duct [-h] [-p OUTPUT_PREFIX] [--sample-interval SAMPLE_INTERVAL] [--report-interval REPORT_INTERVAL] [-c {all,none,stdout,stderr}] [-o {all,none,stdout,stderr}]
            [-t {all,system-summary,processes-samples}]
            command [arguments ...]

```

looks like

```
usage: duct [-h] [-p OUTPUT_PREFIX] [--sample-interval SAMPLE_INTERVAL] [--report-interval REPORT_INTERVAL] [-c {all,none,stdout,stderr}] [-o {all,none,stdout,stderr}]
            [-t {all,system-summary,processes-samples}]
            [--] command [arguments ...]
```

and add description on `--` as to be recommended to ensure that `arguments` are not treated as arguments to `duct`.

On the other hand, I think we might need to look into how to tune argparser here: ideally we should automagically stop parsing when reaching `command`.  @jwodder , you did some heavy CLI parsing tune up in datalad-installer, may be you know what would be the best way here to ensure that parsing stops and `[arguments]` for the `command` do not interfer with our `duct ` arguments?

**Comment by jwodder** [comment]
@yarikoptic Unless `duct` is calling [`parser.parse_intermixed_args()`](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_intermixed_args), I think it should stop at the first non-option argument by default.

**Comment by asmacdo** [comment]
duct is using  `parser.parse_args()`

https://github.com/con/duct/blob/0eec46d9c7527a7f17d3205447223f27b622aa87/src/duct.py#L271

**Comment by yarikoptic** [comment]
not quite -- it does consume `[arguments]` and spits out error, e.g. we get

![image](https://github.com/con/duct/assets/39889/05e31be1-58b9-45eb-b8b6-4a1895347f51)

for 
```
yoh@typhon:/tmp/repro-TccSlQF/ds000003-qc$ cat .datalad/config 
[datalad "dataset"]
        id = 621f77c3-4a35-4147-8146-67fa49b66369
[datalad "containers.bids-mriqc"]
        image = containers/images/bids/bids-mriqc--0.16.0.sing
        cmdexec = duct {img_dspath}/containers/scripts/singularity_cmd run {img} {cmd}
```

in repronim/containers - I had to add `--` after duct there

**Comment by jwodder** [comment]
Then try [`parse_known_args()`](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_args) instead.

**Comment by jwodder** [comment]
Is there a reason you need to use argparse in the first place?  Click is really the better option for both [this sort of thing](https://click.palletsprojects.com/en/8.1.x/advanced/#forwarding-unknown-options) and in general.

**Comment by asmacdo** [comment]
We wanted duct to be "pure" to be as portable as possible.

**Comment by jwodder** [comment]
The undocumented `nargs` value `argparse.REMAINDER` should do what you want:

```
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-f", "--foo")
parser.add_argument("rest", nargs=argparse.REMAINDER)

print(parser.parse_args(["bar", "--foo", "quux"]))
# Prints: Namespace(foo=None, rest=['bar', '--foo', 'quux'])
```
