### ISSUE TITLE
Provide a test for correct handling of args

### ISSUE THREAD

**Issue by yarikoptic** [con/duct#58]
In follow up to 

- https://github.com/con/duct/pull/56

should test parsing (no need to execute) of following command lines

- `duct cmd --help` returns composition of options so --help goes for `cmd`
- `duct --help cmd` returns composition of options so --help goes for `duct`
- `duct --unknown cmd` fails to find `--unknown`
- `duct --unknown cmd --option` fails to find `--unknown`
- `duct --unknown cmd --option` fails
- `duct --sample-interval SAMPLE_INTERVAL` fails (no cmd)

etc, to cover corner cases of possible ways users try to specify smth peculiar.  That is where parametric test specification could be quite handy

**Comment by asmacdo** [comment]
Thanks for the test cases!

**Comment by yarikoptic** [comment]
do we have tests which cover those cases already?
