### ISSUE TITLE
Remove color from output

### ISSUE THREAD

**Issue by yarikoptic** [con/duct#65]
- Causes underlying process to loose its ANSI coloring
- Seems to not doing reset of ANSI coloring after printing its summary
- Seems need to make sure that underlying process is done before printing summary?

Running singularity directly -- results in colors for WARNING and FATAL

![image](https://github.com/con/duct/assets/39889/1ede6d2d-4e25-45ac-aeba-77149a59a20f)

Running through DUCT produced

![image](https://github.com/con/duct/assets/39889/b6c8473b-55cc-457d-9de2-306f241e9ec7)

where no color for WARNING, and FATAL comes at the end in blue.
Both messages are (without ANSI colors) in stderr

```
(dev3) yoh@typhon:/mnt/DATA/data/yoh/1076_spacetop$ cat .duct/logs/2024.06.09T12.47.28-2020941_stderr 
WARNING: skipping mount of /mnt/DATA/data/yoh/1076_spacetop/derivatives: stat /mnt/DATA/data/yoh/1076_spacetop/derivatives: no such file or directory
FATAL:   container creation failed: mount /mnt/DATA/data/yoh/1076_spacetop/derivatives->/mnt/DATA/data/yoh/1076_spacetop/derivatives error: while mounting /mnt/DATA/data/yoh/1076_spacetop/derivatives: mount source /mnt/DATA/data/yoh/1076_spacetop/derivatives doesn't exist
```

**Comment by asmacdo** [comment]
I like the colors, but its not worth adding complexity at the moment, IMO.
