### ISSUE TITLE
Setup automated releases

### ISSUE THREAD

**Issue by yarikoptic** [con/duct#7]
Just also follow datalad-installer setup.

**Comment by yarikoptic** [comment]
Let's close with the first release to appear on both github and pypi. I don't think we need containers for this little thing.

**Comment by yarikoptic** [comment]
are we there yet?

**Comment by asmacdo** [comment]
Next up after dandi migration

**Comment by asmacdo** [comment]
Done via https://github.com/con/duct/pull/113
