### ISSUE TITLE
Question regarding the intended behavior of `update_max_resources()` for "timestamp" fields

### ISSUE THREAD

**Issue by jwodder** [con/duct#99]
Currently, [`Report.update_max_resources()`](https://github.com/con/duct/blob/1c0bfee3173465e4e356faa2bd9cc42201e850fa/src/duct.py#L118-L125) handles the [`"timestamp"`](https://github.com/con/duct/blob/1c0bfee3173465e4e356faa2bd9cc42201e850fa/src/duct.py#L153) fields in process stat dicts by just selecting the larger (i.e., later) of the two.  However, this does not seem very useful or sensible; if any of a process's stats decrease between samplings, the timestamp will end up having no relation to one of more of the "max" stats.  Just what is the desired behavior for timestamps here?

CC @asmacdo @yarikoptic

**Comment by asmacdo** [comment]
Its not useful, but I figured it doesn't do any harm, and it was simpler to just iterate over all fields. The timestamp in the maxes is always the timestamp of the last sample collected, but these intermediate samples aren't reported until they are collated each <report_interval>, so the report shows the timestamp of the final sample collected.

We don't include timestamp in the maxes, so AFAICT its not incorrect even if it is a little clunky.

**Comment by asmacdo** [comment]
I think this is covered, please reopen if not
